export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//WHEN WE SET COOKIESS THEN IN EACH REFRESH WE r gonna send request so We use this these types
//GET COKIES FROM AND SENDING RQUEST TO GET USER INFORMATIONS

export const LOAD_USER_REQUEST_CHECK_PERMIT = "LOAD_USER_REQUEST_CHECK_PERMIT";
export const LOAD_USER_SUCCESS_CHECK_PERMIT = "LOAD_USER_SUCCESS_CHECK_PERMIT";
export const LOAD_USER_FAIL_CHECK_PERMIT = "LOAD_USER_FAIL_CHECK_PERMIT";

//**** */
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

